/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AnypointCombobox.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css} from 'lit-element';

import {AnypointInput} from '@anypoint-web-components/anypoint-input/src/AnypointInput.js';

export {AnypointCombobox};

declare namespace UiElements {

  /**
   * `anypoint-combobox`
   */
  class AnypointCombobox extends AnypointInput {

    /**
     * List of suggestions to display.
     * If the array items are strings they will be used for display a suggestions and
     * to insert a value.
     * If the list is an object the each object must contain `value` and `display`
     * properties.
     * The `display` property will be used in the suggestions list and the
     * `value` property will be used to insert the value to the referenced text field.
     */
    source: any[]|null|undefined;
    render(): any;
    _onActivate(): void;
    firstUpdated(): void;
  }
}
